apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rollouts-demo
spec:
  rules:
  - host: rollouts-demo.eqslearning.com
    http:
      paths:
      - path: /
        backend:
          serviceName: rollouts-demo
          servicePort: 80
