--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: front-end
  namespace: sock-shop
spec: 
  hosts: 
    - front-end
  http: 
    - 
      fault: 
        abort: 
          httpStatus: 500
          percent: 100
      route: 
        - 
          destination: 
            host: front-end
            subset: v1
