apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: istio-system
  name: istio-system

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: tools
  name: tools

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: demo
  name: demo
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: istio-demo
  name: istio-demo