apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-setup
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd

spec:
  # The project the application belongs to.
  project: tools

  # Source of the application manifests
  source:
    repoURL: https://github.com/naveenkumarsp/srek8gitops.git
    targetRevision: HEAD
    path: k8sbootstrap/istio-setup

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
