apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-demo
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd

spec:
  # The project the application belongs to.
  project: demo

  # Source of the application manifests
  source:
    repoURL: https://github.com/naveenkumarsp/srek8gitops.git
    targetRevision: HEAD
    path: applications/istioapps

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-demo

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    validate: true # Validate resources before applying to k8s, defaults to true.